export const SOUNDS = [
 require('../assets/mailboxbadgerdrumsamplesvolume2/\"Good\".mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/\"okay\".mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/\(ha\).mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/7:1-80Hz\ Squarewave.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/7:1-Square\ Wave\ Low\ Tom.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/10:30.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/440hat10:30:2015.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/aerosol\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/aerosol\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Aerosol\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Aerosol\ 5.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Airhorn.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Clap\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Clave\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Clave\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Clave\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Conga\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Conga\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Cymbal\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Cymbal\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Cymbal\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Cymbal\ 4.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Cymbal\ 5.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Cymbal\ 6.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Hihat\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Hihat\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Kick\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Kick\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Kick\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Kick\ 4.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Low\ Tom\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Low\ Tom\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Snare\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Snare\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Snare\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Analog\ Snare\ 4.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Applause.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/bananapeelslip.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Boo.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Bow\ and\ Arrow.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Buzz\ 2-10:30:2015.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Buzz-10:30:2015.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Cat\ Call.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Crickets\ Birds\ Frogs\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Crickets\ Birds\ Frogs\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Crickets\ Birds\ Frogs\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Crickets\ Birds\ Frogs\ 4.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Crickets\ Birds\ Frogs\ 5.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Crickets\ Birds\ Frogs\ 6.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Crickets\ Birds\ Frogs\ 7.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Crickets\ Birds\ Frogs\ Samples.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Cymbal\ -\ 5:2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Death\ Sound.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Dial\ tone.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Drizzle.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Eep.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Electronic\ Cowbell\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Electronic\ Hi\ Tom\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Electronic\ Kick\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Electronic\ Kick\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Electronic\ Low\ Tom.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Electronic\ Mid\ Tom\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Electronic\ Snare\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Electronic\ Snare\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Electronic\ Tambourine\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fart.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/FBMessage.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-\ Aux\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-\ Aux\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-\ Aux\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-\ Aux\ 4.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-\ Aux\ 5.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-\ Aux\ 6.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-\ Aux\ 7.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-Bass\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-Bass\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-Bass\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-Bass\ 4.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-Snare\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-Snare\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-Snare\ 4.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Fireworks-Snare.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Funk.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Closed\ Hihat.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Conga.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Cowbell.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Crash.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Kick\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Kick\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Kick\ 57slower.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Low\ Tom.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Open\ Hihat.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Ride\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Ride.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Cl\ Hihat.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Clap\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Crash\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Crash-57slower.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Crash.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Hi\ Tom.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Kick\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Kick\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Low\ Tom.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Mid\ Tom.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Open\ Hihat.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Ride.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Snare\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Snare\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Room\ Stick\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Snare\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Snare\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Tambourine.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/General\ Tom.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Glass\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Glass\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Glass\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Glass\ 4.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Glass\ Breaking\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Glass\ Breaking\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Glass\ Breaking\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Glass\ Breaking\ 4.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/HeeHaw.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Hi\ Tom-5:2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/hi\ tom-10:30:2015.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/HiHat-\ 5:2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Kick-\ 5:2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Kick-\ 10:30:2015.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/kick-6:9:2015.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/KO.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Korg\ Metronome\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Korg\ Metronome\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Low\ Tom\ 1\ -\ 5:2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Low\ tom\ 2\ -\ 5:2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Maclert.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Metronome\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Metronome\ 2.mp3'),
 require('..lause.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/noizehat1-10:30:2015.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/point07sec\ brown\ noise.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/point07sec\ pink\ noise.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/porta-hatopen-57slower.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/portas-cl-hihat-57slower.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Quack.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Rain\ Samples.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Rain\ Spout\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Rain\ Spout\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Rain\ Spout\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/RFI.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Ringing.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/ris\ kik.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Risset\ Drum\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Risset\ Drum\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Risset\ Drum\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Risset\ drum\ conga.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Risset\ Drum\ lo\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Risset\ Drum\ loose\ lo\ tom.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Risset\ Drum\ Low.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Risset\ Drum\ Stick.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Sawtooth\ low.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/sawtooth\ one.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Scream.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/silly\ rimshot.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Smooch.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Snare-\ 5:2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Sosumi.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Sprung.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Startup1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Startup2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Startup3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Stick\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/stick\ 2-10:30:2015.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Stick\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Stick-10:30:2015.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Submarine.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Switch\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Switch\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Switch\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Switch\ Samples.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Clap\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Click\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Crash\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Hihat\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Hihat\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Kick\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Kick\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Ride\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Snare\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Snare\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Tom\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Tom\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Techno\ Tom\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Thunder\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Thunder\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Tink.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Tough\ Luck.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Vibration.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Volume\ Click.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Wah.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/wood\ splitting\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Wood\ Splitting\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Wood\ Splitting\ 4.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Bongo\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Coffee\ Cup.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Conga\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Conga\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Conga\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Conga\ 4.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Guiro.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Shaker\ .mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Shaker\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Timbale\ 1.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Timbale\ 2.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Timbale\ 3.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Latin-Wood\ Block.mp3'),
 require('../assets/mailboxbadgerdrumsamplesvolume2/Zoom\ Timbale\ 2.mp3')
];

